name: Publish
on:
  push:
    paths: ["lang/**", ".github/workflows/update.yaml"]
  workflow_dispatch:
jobs:
  build:
    name: Publish binaries
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: |
        python script.py
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: lang/*.json
        tag: "lang"
        overwrite: true
        file_glob: true
    - name: Checkout target repository
      uses: actions/checkout@v4
      with:
        repository: "gamemgh/gamemgh.github.io"
        token: ${{ secrets.TK }}
        path: "gamemgh.github.io"
    - name: Copy renamed configs to target repository
      run: |
        rm -f gamemgh.github.io/Web/data/langs/*.toml
        cp json/*.json "gamemgh.github.io/Web/data/lang/"
    - name: Check for changes
      run: |
        cd "gamemgh.github.io"
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add .
        if git diff --staged --quiet; then
          echo "No changes to commit"
          exit 0
        fi
        git commit -m "Sync language configs" -a
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.TK }}
        path: "gamemgh.github.io"
        branch: update-language-configs
        branch-suffix: 'timestamp'
        commit-message: "Sync language configs"
        title: "Update language configuration files"
        body: "This PR updates or adds language configuration files."
        delete-branch: true